//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bacc_front.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameSetting {
            get {
                return ((string)(this["GameSetting"]));
            }
            set {
                this["GameSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _isGameInited {
            get {
                return ((bool)(this["_isGameInited"]));
            }
            set {
                this["_isGameInited"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentSessionIndex {
            get {
                return ((int)(this["CurrentSessionIndex"]));
            }
            set {
                this["CurrentSessionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JsonPlayerScores {
            get {
                return ((string)(this["JsonPlayerScores"]));
            }
            set {
                this["JsonPlayerScores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerUrl {
            get {
                return ((string)(this["ServerUrl"]));
            }
            set {
                this["ServerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2BDQdbYmfKjQXPjeWEFdBA==")]
        public string AdministratorPwd {
            get {
                return ((string)(this["AdministratorPwd"]));
            }
            set {
                this["AdministratorPwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TvLi6ZcIlR/y+wfWr2gFeg==")]
        public string waiter_pwd {
            get {
                return ((string)(this["waiter_pwd"]));
            }
            set {
                this["waiter_pwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1jB7mL0Ap15jh9UoSb2LEw==")]
        public string manager_pwd {
            get {
                return ((string)(this["manager_pwd"]));
            }
            set {
                this["manager_pwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X0LvbxCGKj6zlK01F1XxXQ==")]
        public string boss_pwd {
            get {
                return ((string)(this["boss_pwd"]));
            }
            set {
                this["boss_pwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("otV9Ro5ebUsknIyHD8WZnQ==")]
        public string audit_account_pwd {
            get {
                return ((string)(this["audit_account_pwd"]));
            }
            set {
                this["audit_account_pwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mxFwyn3f/izsEE/xasED4w==")]
        public string quit_front_pwd {
            get {
                return ((string)(this["quit_front_pwd"]));
            }
            set {
                this["quit_front_pwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3Sz2sBHexyH4zsfpidi7qA==")]
        public string shutdown_pwd {
            get {
                return ((string)(this["shutdown_pwd"]));
            }
            set {
                this["shutdown_pwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8dTKG4Iz3i4K6I1mOf+Eag==")]
        public string clear_account_pwd {
            get {
                return ((string)(this["clear_account_pwd"]));
            }
            set {
                this["clear_account_pwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("krblvv6kZ1s8L9wgeEnv4Q==")]
        public string audit_bet_record_pwd {
            get {
                return ((string)(this["audit_bet_record_pwd"]));
            }
            set {
                this["audit_bet_record_pwd"] = value;
            }
        }
    }
}
